name: FortiDevSec Scanner CI 
on:
  push:
   branches: [ master ]
  pull_request:
   branches: [ master ]
 
jobs:
  testing:
   runs-on: ubuntu-latest    
   steps:
   - uses: actions/checkout@v2
   - name: 'Install Node'
     uses: actions/setup-node@v1
   - name: Start app
     run: npm start &
   - name: "Run Test"
     run:  curl http://127.0.0.1:8081
     
  scanning:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v2
   - name: SAST
     run: |
      docker pull registry.fortidevsec.forticloud.com/fdevsec_sast:latest
      docker run -i --mount type=bind,source="$(pwd)",target=/scan  registry.fortidevsec.forticloud.com/fdevsec_sast:latest
